### ISSUE TITLE
Date (incorrectly) appears before priority

### ISSUE THREAD

**Issue by hrbellemare** [DoctorRadar/todotxt_cli_date_add#2]
From the [todo.txt format rules](https://github.com/todotxt/todo.txt/blob/master/README.md):

Rule 1: If priority exists, it ALWAYS appears first.
[An example from later in the file:] (A) 2011-03-02 Call Mom

Currently, this is what happens when I include a priority:

2020-08-06 (A) Check voicemail

**Comment by DoctorRadar** [comment]
Good spot. I'll have a look at that ASAP. Full disclosure: I tend not to use priorities, so I didn't consider that case.

**Comment by DoctorRadar** [comment]
I updated the script to correct this.
